# 自分のPCで動かす時の設定
# アプリ名
spring.application.name=MediaReviewApp

# H2 Databaseの設定
spring.datasource.url=jdbc:h2:mem:mediadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Consoleを有効にする（ブラウザでDBが見れるようになる）
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernateの設定（Entityからテーブルを自動作成する）
spring.jpa.hibernate.ddl-auto=update
# 実行されるSQLをログに表示する（デバッグに便利）
spring.jpa.show-sql=true

# 最初の1回目でも、URLに「;jsessionid」を絶対に付けないようにする設定
server.servlet.session.tracking-modes=cookie